#!/bin/bash
SCRIPT_PATH="`readlink -f "$0"`"
HERE="`dirname "$SCRIPT_PATH"`"
LD_LIBRARY_PATH="$HERE:$HERE/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH
filename=$HERE/multiple-bin
if [ -e $filename ]
then
    exec -a "$0" "$filename"  "$@"
else
    echo "error: execute 'make' to compile the project before using"
fi

